sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59svg qt59x11extras

script:
  - source /opt/qt59/bin/qt59-env.sh
  - /opt/qt59/bin/qmake
  - make
