######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 2 23:02:23 2009
######################################################################

TEMPLATE = app
TARGET = qsvgthemeviewer
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = bin

# Input
HEADERS += ThemePreviewUI.h
FORMS += ThemePreviewUIBase.ui
SOURCES += main.cpp ThemePreviewUI.cpp
RESOURCES += ThemePreviewUIResources.qrc
